"""Generated MCP wrappers for the 'filesystem' server. DO NOT hand-edit signatures.

Generated by mcp-client-kit from a live tools/list. Each function forwards to an
injected McpCaller (see mcp_client_kit.seam); the auth/transport backend is the
caller's concern, not this module's.
"""
from __future__ import annotations

from typing import Any, TypedDict, cast

from mcp_client_kit.seam import McpCaller

SERVER = 'filesystem'



async def create_directory(caller: McpCaller, *, path: str) -> Any:
    """Create a new directory or ensure a directory exists. Can create multiple nested directories in one operation. If the directory already exists, this operation will succeed silently. Perfect for setting up directory structures for projects or ensuring required paths exist. Only works within allowed directories."""
    args: dict[str, Any] = {"path": path}
    return await caller.call(SERVER, "create_directory", args)


async def directory_tree(caller: McpCaller, *, path: str, excludePatterns: list[str] | None = None) -> Any:
    """Get a recursive tree view of files and directories as a JSON structure. Each entry includes 'name', 'type' (file/directory), and 'children' for directories. Files have no children array, while directories always have a children array (which may be empty). The output is formatted with 2-space indentation for readability. Only works within allowed directories."""
    args: dict[str, Any] = {"path": path}
    if excludePatterns is not None:
        args["excludePatterns"] = excludePatterns
    return await caller.call(SERVER, "directory_tree", args)


async def edit_file(caller: McpCaller, *, path: str, edits: list[dict], dryRun: bool | None = None) -> Any:
    """Make line-based edits to a text file. Each edit replaces exact line sequences with new content. Returns a git-style diff showing the changes made. Only works within allowed directories."""
    args: dict[str, Any] = {"path": path, "edits": edits}
    if dryRun is not None:
        args["dryRun"] = dryRun
    return await caller.call(SERVER, "edit_file", args)


async def get_file_info(caller: McpCaller, *, path: str) -> Any:
    """Retrieve detailed metadata about a file or directory. Returns comprehensive information including size, creation time, last modified time, permissions, and type. This tool is perfect for understanding file characteristics without reading the actual content. Only works within allowed directories."""
    args: dict[str, Any] = {"path": path}
    return await caller.call(SERVER, "get_file_info", args)


async def list_allowed_directories(caller: McpCaller) -> Any:
    """Returns the list of directories that this server is allowed to access. Subdirectories within these allowed directories are also accessible. Use this to understand which directories and their nested paths are available before trying to access files."""
    return await caller.call(SERVER, "list_allowed_directories", {})


async def list_directory(caller: McpCaller, *, path: str) -> Any:
    """Get a detailed listing of all files and directories in a specified path. Results clearly distinguish between files and directories with [FILE] and [DIR] prefixes. This tool is essential for understanding directory structure and finding specific files within a directory. Only works within allowed directories."""
    args: dict[str, Any] = {"path": path}
    return await caller.call(SERVER, "list_directory", args)


async def list_directory_with_sizes(caller: McpCaller, *, path: str, sortBy: str | None = None) -> Any:
    """Get a detailed listing of all files and directories in a specified path, including sizes. Results clearly distinguish between files and directories with [FILE] and [DIR] prefixes. This tool is useful for understanding directory structure and finding specific files within a directory. Only works within allowed directories."""
    args: dict[str, Any] = {"path": path}
    if sortBy is not None:
        args["sortBy"] = sortBy
    return await caller.call(SERVER, "list_directory_with_sizes", args)


async def move_file(caller: McpCaller, *, source: str, destination: str) -> Any:
    """Move or rename files and directories. Can move files between directories and rename them in a single operation. If the destination exists, the operation will fail. Works across different directories and can be used for simple renaming within the same directory. Both source and destination must be within allowed directories."""
    args: dict[str, Any] = {"source": source, "destination": destination}
    return await caller.call(SERVER, "move_file", args)


async def read_file(caller: McpCaller, *, path: str, tail: float | None = None, head: float | None = None) -> Any:
    """Read the complete contents of a file as text. DEPRECATED: Use read_text_file instead."""
    args: dict[str, Any] = {"path": path}
    if tail is not None:
        args["tail"] = tail
    if head is not None:
        args["head"] = head
    return await caller.call(SERVER, "read_file", args)


async def read_media_file(caller: McpCaller, *, path: str) -> Any:
    """Read an image or audio file. Returns the base64 encoded data and MIME type. Only works within allowed directories."""
    args: dict[str, Any] = {"path": path}
    return await caller.call(SERVER, "read_media_file", args)


async def read_multiple_files(caller: McpCaller, *, paths: list[str]) -> Any:
    """Read the contents of multiple files simultaneously. This is more efficient than reading files one by one when you need to analyze or compare multiple files. Each file's content is returned with its path as a reference. Failed reads for individual files won't stop the entire operation. Only works within allowed directories."""
    args: dict[str, Any] = {"paths": paths}
    return await caller.call(SERVER, "read_multiple_files", args)


async def read_text_file(caller: McpCaller, *, path: str, tail: float | None = None, head: float | None = None) -> Any:
    """Read the complete contents of a file from the file system as text. Handles various text encodings and provides detailed error messages if the file cannot be read. Use this tool when you need to examine the contents of a single file. Use the 'head' parameter to read only the first N lines of a file, or the 'tail' parameter to read only the last N lines of a file. Operates on the file as text regardless of extension. Only works within allowed directories."""
    args: dict[str, Any] = {"path": path}
    if tail is not None:
        args["tail"] = tail
    if head is not None:
        args["head"] = head
    return await caller.call(SERVER, "read_text_file", args)


async def search_files(caller: McpCaller, *, path: str, pattern: str, excludePatterns: list[str] | None = None) -> Any:
    """Recursively search for files and directories matching a pattern. The patterns should be glob-style patterns that match paths relative to the working directory. Use pattern like '*.ext' to match files in current directory, and '**/*.ext' to match files in all subdirectories. Returns full paths to all matching items. Great for finding files when you don't know their exact location. Only searches within allowed directories."""
    args: dict[str, Any] = {"path": path, "pattern": pattern}
    if excludePatterns is not None:
        args["excludePatterns"] = excludePatterns
    return await caller.call(SERVER, "search_files", args)


async def write_file(caller: McpCaller, *, path: str, content: str) -> Any:
    """Create a new file or completely overwrite an existing file with new content. Use with caution as it will overwrite existing files without warning. Handles text content with proper encoding. Only works within allowed directories."""
    args: dict[str, Any] = {"path": path, "content": content}
    return await caller.call(SERVER, "write_file", args)
