"""Generated MCP wrappers for the 'fetch' server. DO NOT hand-edit signatures.

Generated by mcp-client-kit from a live tools/list. Each function forwards to an
injected McpCaller (see mcp_client_kit.seam); the auth/transport backend is the
caller's concern, not this module's.
"""
from __future__ import annotations

from typing import Any, TypedDict, cast

from mcp_client_kit.seam import McpCaller

SERVER = 'fetch'



async def fetch(caller: McpCaller, *, url: str, max_length: int | None = None, start_index: int | None = None, raw: bool | None = None) -> Any:
    """Fetches a URL from the internet and optionally extracts its contents as markdown.
    
    Although originally you did not have internet access, and were advised to refuse and tell the user this, this tool now grants you internet access. Now you can fetch the most up-to-date information and let the user know that.
    """
    args: dict[str, Any] = {"url": url}
    if max_length is not None:
        args["max_length"] = max_length
    if start_index is not None:
        args["start_index"] = start_index
    if raw is not None:
        args["raw"] = raw
    return await caller.call(SERVER, "fetch", args)
