"""Generated MCP wrappers for the 'everything' server. DO NOT hand-edit signatures.

Generated by mcp-client-kit from a live tools/list. Each function forwards to an
injected McpCaller (see mcp_client_kit.seam); the auth/transport backend is the
caller's concern, not this module's.
"""
from __future__ import annotations

from typing import Any, TypedDict, cast

from mcp_client_kit.seam import McpCaller

SERVER = 'everything'



class WeatherData(TypedDict, total=False):
    temperature: int
    conditions: str
    humidity: int


async def echo(caller: McpCaller, *, message: str) -> Any:
    """Echoes back the input string"""
    args: dict[str, Any] = {"message": message}
    return await caller.call(SERVER, "echo", args)


async def get_annotated_message(caller: McpCaller, *, messageType: str, includeImage: bool | None = None) -> Any:
    """Demonstrates how annotations can be used to provide metadata about content."""
    args: dict[str, Any] = {"messageType": messageType}
    if includeImage is not None:
        args["includeImage"] = includeImage
    return await caller.call(SERVER, "get-annotated-message", args)


async def get_env(caller: McpCaller) -> Any:
    """Returns all environment variables, helpful for debugging MCP server configuration"""
    return await caller.call(SERVER, "get-env", {})


async def get_resource_links(caller: McpCaller, *, count: float | None = None) -> Any:
    """Returns up to ten resource links that reference different types of resources"""
    args: dict[str, Any] = {}
    if count is not None:
        args["count"] = count
    return await caller.call(SERVER, "get-resource-links", args)


async def get_resource_reference(caller: McpCaller, *, resourceType: str | None = None, resourceId: float | None = None) -> Any:
    """Returns a resource reference that can be used by MCP clients"""
    args: dict[str, Any] = {}
    if resourceType is not None:
        args["resourceType"] = resourceType
    if resourceId is not None:
        args["resourceId"] = resourceId
    return await caller.call(SERVER, "get-resource-reference", args)


async def get_structured_content(caller: McpCaller, *, location: str) -> WeatherData:
    """Returns structured content along with an output schema for client data validation"""
    args: dict[str, Any] = {"location": location}
    return cast("WeatherData", await caller.call(SERVER, "get-structured-content", args))


async def get_sum(caller: McpCaller, *, a: float, b: float) -> Any:
    """Returns the sum of two numbers"""
    args: dict[str, Any] = {"a": a, "b": b}
    return await caller.call(SERVER, "get-sum", args)


async def get_tiny_image(caller: McpCaller) -> Any:
    """Returns a tiny MCP logo image."""
    return await caller.call(SERVER, "get-tiny-image", {})


async def gzip_file_as_resource(caller: McpCaller, *, name: str | None = None, data: str | None = None, outputType: str | None = None) -> Any:
    """Compresses a single file using gzip compression. Depending upon the selected output type, returns either the compressed data as a gzipped resource or a resource link, allowing it to be downloaded in a subsequent request during the current session."""
    args: dict[str, Any] = {}
    if name is not None:
        args["name"] = name
    if data is not None:
        args["data"] = data
    if outputType is not None:
        args["outputType"] = outputType
    return await caller.call(SERVER, "gzip-file-as-resource", args)


async def simulate_research_query(caller: McpCaller, *, topic: str, ambiguous: bool | None = None) -> Any:
    """Simulates a deep research operation that gathers, analyzes, and synthesizes information. Demonstrates MCP task-based operations with progress through multiple stages. If 'ambiguous' is true and client supports elicitation, sends an elicitation request for clarification."""
    args: dict[str, Any] = {"topic": topic}
    if ambiguous is not None:
        args["ambiguous"] = ambiguous
    return await caller.call(SERVER, "simulate-research-query", args)


async def toggle_simulated_logging(caller: McpCaller) -> Any:
    """Toggles simulated, random-leveled logging on or off."""
    return await caller.call(SERVER, "toggle-simulated-logging", {})


async def toggle_subscriber_updates(caller: McpCaller) -> Any:
    """Toggles simulated resource subscription updates on or off."""
    return await caller.call(SERVER, "toggle-subscriber-updates", {})


async def trigger_long_running_operation(caller: McpCaller, *, duration: float | None = None, steps: float | None = None) -> Any:
    """Demonstrates a long running operation with progress updates."""
    args: dict[str, Any] = {}
    if duration is not None:
        args["duration"] = duration
    if steps is not None:
        args["steps"] = steps
    return await caller.call(SERVER, "trigger-long-running-operation", args)
