"""Generated MCP wrappers for the 'git' server. DO NOT hand-edit signatures.

Generated by mcp-client-kit from a live tools/list. Each function forwards to an
injected McpCaller (see mcp_client_kit.seam); the auth/transport backend is the
caller's concern, not this module's.
"""
from __future__ import annotations

from typing import Any, TypedDict, cast

from mcp_client_kit.seam import McpCaller

SERVER = 'git'



async def git_add(caller: McpCaller, *, repo_path: str, files: list[str]) -> Any:
    """Adds file contents to the staging area"""
    args: dict[str, Any] = {"repo_path": repo_path, "files": files}
    return await caller.call(SERVER, "git_add", args)


async def git_branch(caller: McpCaller, *, repo_path: str, branch_type: str, contains: Any | None = None, not_contains: Any | None = None) -> Any:
    """List Git branches"""
    args: dict[str, Any] = {"repo_path": repo_path, "branch_type": branch_type}
    if contains is not None:
        args["contains"] = contains
    if not_contains is not None:
        args["not_contains"] = not_contains
    return await caller.call(SERVER, "git_branch", args)


async def git_checkout(caller: McpCaller, *, repo_path: str, branch_name: str) -> Any:
    """Switches branches"""
    args: dict[str, Any] = {"repo_path": repo_path, "branch_name": branch_name}
    return await caller.call(SERVER, "git_checkout", args)


async def git_commit(caller: McpCaller, *, repo_path: str, message: str) -> Any:
    """Records changes to the repository"""
    args: dict[str, Any] = {"repo_path": repo_path, "message": message}
    return await caller.call(SERVER, "git_commit", args)


async def git_create_branch(caller: McpCaller, *, repo_path: str, branch_name: str, base_branch: Any | None = None) -> Any:
    """Creates a new branch from an optional base branch"""
    args: dict[str, Any] = {"repo_path": repo_path, "branch_name": branch_name}
    if base_branch is not None:
        args["base_branch"] = base_branch
    return await caller.call(SERVER, "git_create_branch", args)


async def git_diff(caller: McpCaller, *, repo_path: str, target: str, context_lines: int | None = None) -> Any:
    """Shows differences between branches or commits"""
    args: dict[str, Any] = {"repo_path": repo_path, "target": target}
    if context_lines is not None:
        args["context_lines"] = context_lines
    return await caller.call(SERVER, "git_diff", args)


async def git_diff_staged(caller: McpCaller, *, repo_path: str, context_lines: int | None = None) -> Any:
    """Shows changes that are staged for commit"""
    args: dict[str, Any] = {"repo_path": repo_path}
    if context_lines is not None:
        args["context_lines"] = context_lines
    return await caller.call(SERVER, "git_diff_staged", args)


async def git_diff_unstaged(caller: McpCaller, *, repo_path: str, context_lines: int | None = None) -> Any:
    """Shows changes in the working directory that are not yet staged"""
    args: dict[str, Any] = {"repo_path": repo_path}
    if context_lines is not None:
        args["context_lines"] = context_lines
    return await caller.call(SERVER, "git_diff_unstaged", args)


async def git_log(caller: McpCaller, *, repo_path: str, max_count: int | None = None, start_timestamp: Any | None = None, end_timestamp: Any | None = None) -> Any:
    """Shows the commit logs"""
    args: dict[str, Any] = {"repo_path": repo_path}
    if max_count is not None:
        args["max_count"] = max_count
    if start_timestamp is not None:
        args["start_timestamp"] = start_timestamp
    if end_timestamp is not None:
        args["end_timestamp"] = end_timestamp
    return await caller.call(SERVER, "git_log", args)


async def git_reset(caller: McpCaller, *, repo_path: str) -> Any:
    """Unstages all staged changes"""
    args: dict[str, Any] = {"repo_path": repo_path}
    return await caller.call(SERVER, "git_reset", args)


async def git_show(caller: McpCaller, *, repo_path: str, revision: str) -> Any:
    """Shows the contents of a commit"""
    args: dict[str, Any] = {"repo_path": repo_path, "revision": revision}
    return await caller.call(SERVER, "git_show", args)


async def git_status(caller: McpCaller, *, repo_path: str) -> Any:
    """Shows the working tree status"""
    args: dict[str, Any] = {"repo_path": repo_path}
    return await caller.call(SERVER, "git_status", args)
