"""Generated MCP wrappers for the 'memory' server. DO NOT hand-edit signatures.

Generated by mcp-client-kit from a live tools/list. Each function forwards to an
injected McpCaller (see mcp_client_kit.seam); the auth/transport backend is the
caller's concern, not this module's.
"""
from __future__ import annotations

from typing import Any, TypedDict, cast

from mcp_client_kit.seam import McpCaller

SERVER = 'memory'



class KnowledgeGraph(TypedDict, total=False):
    entities: list
    relations: list


class KnowledgeGraph(TypedDict, total=False):
    entities: list
    relations: list


class KnowledgeGraph(TypedDict, total=False):
    entities: list
    relations: list


async def add_observations(caller: McpCaller, *, observations: list[dict]) -> Any:
    """Add new observations to existing entities in the knowledge graph"""
    args: dict[str, Any] = {"observations": observations}
    return await caller.call(SERVER, "add_observations", args)


async def create_entities(caller: McpCaller, *, entities: list[dict]) -> Any:
    """Create multiple new entities in the knowledge graph"""
    args: dict[str, Any] = {"entities": entities}
    return await caller.call(SERVER, "create_entities", args)


async def create_relations(caller: McpCaller, *, relations: list[dict]) -> Any:
    """Create multiple new relations between entities in the knowledge graph. Relations should be in active voice"""
    args: dict[str, Any] = {"relations": relations}
    return await caller.call(SERVER, "create_relations", args)


async def delete_entities(caller: McpCaller, *, entityNames: list[str]) -> Any:
    """Delete multiple entities and their associated relations from the knowledge graph"""
    args: dict[str, Any] = {"entityNames": entityNames}
    return await caller.call(SERVER, "delete_entities", args)


async def delete_observations(caller: McpCaller, *, deletions: list[dict]) -> Any:
    """Delete specific observations from entities in the knowledge graph"""
    args: dict[str, Any] = {"deletions": deletions}
    return await caller.call(SERVER, "delete_observations", args)


async def delete_relations(caller: McpCaller, *, relations: list[dict]) -> Any:
    """Delete multiple relations from the knowledge graph"""
    args: dict[str, Any] = {"relations": relations}
    return await caller.call(SERVER, "delete_relations", args)


async def open_nodes(caller: McpCaller, *, names: list[str]) -> KnowledgeGraph:
    """Open specific nodes in the knowledge graph by their names"""
    args: dict[str, Any] = {"names": names}
    return cast("KnowledgeGraph", await caller.call(SERVER, "open_nodes", args))


async def read_graph(caller: McpCaller) -> KnowledgeGraph:
    """Read the entire knowledge graph"""
    return cast("KnowledgeGraph", await caller.call(SERVER, "read_graph", {}))


async def search_nodes(caller: McpCaller, *, query: str) -> KnowledgeGraph:
    """Search for nodes in the knowledge graph based on a query"""
    args: dict[str, Any] = {"query": query}
    return cast("KnowledgeGraph", await caller.call(SERVER, "search_nodes", args))
