"""Generated MCP wrappers for the 'context7' server. DO NOT hand-edit signatures.

Generated by mcp-client-kit from a live tools/list. Each function forwards to an
injected McpCaller (see mcp_client_kit.seam); the auth/transport backend is the
caller's concern, not this module's.
"""
from __future__ import annotations

from typing import Any, TypedDict, cast

from mcp_client_kit.seam import McpCaller

SERVER = 'context7'



async def query_docs(caller: McpCaller, *, libraryId: str, query: str) -> Any:
    """Retrieves and queries up-to-date documentation and code examples from Context7 for any programming library or framework.
    
    You must call 'Resolve Context7 Library ID' tool first to obtain the exact Context7-compatible library ID required to use this tool, UNLESS the user explicitly provides a library ID in the format '/org/project' or '/org/project/version' in their query.
    
    Do not call this tool more than 3 times per question.
    """
    args: dict[str, Any] = {"libraryId": libraryId, "query": query}
    return await caller.call(SERVER, "query-docs", args)


async def resolve_library_id(caller: McpCaller, *, query: str, libraryName: str) -> Any:
    """Resolves a package/product name to a Context7-compatible library ID and returns matching libraries.
    
    You MUST call this function before 'Query Documentation' tool to obtain a valid Context7-compatible library ID UNLESS the user explicitly provides a library ID in the format '/org/project' or '/org/project/version' in their query.
    
    Each result includes:
    - Library ID: Context7-compatible identifier (format: /org/project)
    - Name: Library or package name
    - Description: Short summary
    - Code Snippets: Number of available code examples
    - Source Reputation: Authority indicator (High, Medium, Low, or Unknown)
    - Benchmark Score: Quality indicator (100 is the highest score)
    - Versions: List of versions if available. Use one of those versions if the user provides a version in their query. The format of the version is /org/project/version.
    
    For best results, select libraries based on name match, source reputation, snippet coverage, benchmark score, and relevance to your use case.
    
    Selection Process:
    1. Analyze the query to understand what library/package the user is looking for
    2. Return the most relevant match based on:
    - Name similarity to the query (exact matches prioritized)
    - Description relevance to the query's intent
    - Documentation coverage (prioritize libraries with higher Code Snippet counts)
    - Source reputation (consider libraries with High or Medium reputation more authoritative)
    - Benchmark Score: Quality indicator (100 is the highest score)
    
    Response Format:
    - Return the selected library ID in a clearly marked section
    - Provide a brief explanation for why this library was chosen
    - If multiple good matches exist, acknowledge this but proceed with the most relevant one
    - If no good matches exist, clearly state this and suggest query refinements
    
    For ambiguous queries, request clarification before proceeding with a best-guess match.
    
    IMPORTANT: Do not call this tool more than 3 times per question. If you cannot find what you need after 3 calls, use the best result you have.
    """
    args: dict[str, Any] = {"query": query, "libraryName": libraryName}
    return await caller.call(SERVER, "resolve-library-id", args)
