"""Generated MCP wrappers for the 'codegraph' server. DO NOT hand-edit signatures.

Generated by mcp-client-kit from a live tools/list. Each function forwards to an
injected McpCaller (see mcp_client_kit.seam); the auth/transport backend is the
caller's concern, not this module's.
"""
from __future__ import annotations

from typing import Any, TypedDict, cast

from mcp_client_kit.seam import McpCaller

SERVER = 'codegraph'



async def codegraph_context(caller: McpCaller, *, task: str, maxNodes: float | None = None, includeCode: bool | None = None, projectPath: str | None = None) -> Any:
    """PRIMARY TOOL — call FIRST for any "how does X work"/architecture/bug question. Returns entry points + related symbols + key code in one call; usually answers without further search/Read/Grep. Provides CODE context, not product requirements."""
    args: dict[str, Any] = {"task": task}
    if maxNodes is not None:
        args["maxNodes"] = maxNodes
    if includeCode is not None:
        args["includeCode"] = includeCode
    if projectPath is not None:
        args["projectPath"] = projectPath
    return await caller.call(SERVER, "codegraph_context", args)


async def codegraph_explore(caller: McpCaller, *, query: str, maxFiles: float | None = None, projectPath: str | None = None) -> Any:
    """Source of SEVERAL related symbols grouped by file, in one capped call. Query is a bag of symbol/file names (not a question). Returned source is verbatim Read-equivalent — do not re-open shown files. Prefer over chained codegraph_node. Budget: make at most 1 calls for this project (30 files indexed)."""
    args: dict[str, Any] = {"query": query}
    if maxFiles is not None:
        args["maxFiles"] = maxFiles
    if projectPath is not None:
        args["projectPath"] = projectPath
    return await caller.call(SERVER, "codegraph_explore", args)


async def codegraph_node(caller: McpCaller, *, symbol: str, includeCode: bool | None = None, projectPath: str | None = None) -> Any:
    """One symbol's location, signature, callers/callees trail. includeCode=true returns the verbatim body. Use codegraph_trace for full paths instead of chaining nodes."""
    args: dict[str, Any] = {"symbol": symbol}
    if includeCode is not None:
        args["includeCode"] = includeCode
    if projectPath is not None:
        args["projectPath"] = projectPath
    return await caller.call(SERVER, "codegraph_node", args)


async def codegraph_search(caller: McpCaller, *, query: str, kind: str | None = None, limit: float | None = None, projectPath: str | None = None) -> Any:
    """Quick symbol search by name. Returns locations only (no code). Use codegraph_context instead for comprehensive task context."""
    args: dict[str, Any] = {"query": query}
    if kind is not None:
        args["kind"] = kind
    if limit is not None:
        args["limit"] = limit
    if projectPath is not None:
        args["projectPath"] = projectPath
    return await caller.call(SERVER, "codegraph_search", args)


async def codegraph_trace(caller: McpCaller, *, from_: str, to: str, projectPath: str | None = None) -> Any:
    """Call path between two symbols — "how does <from> reach <to>?" Returns the chain with each hop's body inlined plus the destination's callees, in ONE call. Ideal for flow questions (update→render, request→handler, QuerySet→SQL). If no static path exists the chain broke at dynamic dispatch — the failure response inlines both endpoints + their TO-file siblings."""
    args: dict[str, Any] = {"from": from_, "to": to}
    if projectPath is not None:
        args["projectPath"] = projectPath
    return await caller.call(SERVER, "codegraph_trace", args)
