"""Generated MCP wrappers for the 'sqlite' server. DO NOT hand-edit signatures.

Generated by mcp-client-kit from a live tools/list. Each function forwards to an
injected McpCaller (see mcp_client_kit.seam); the auth/transport backend is the
caller's concern, not this module's.
"""
from __future__ import annotations

from typing import Any, TypedDict, cast

from mcp_client_kit.seam import McpCaller

SERVER = 'sqlite'



async def append_insight(caller: McpCaller, *, insight: str) -> Any:
    """Add a business insight to the memo"""
    args: dict[str, Any] = {"insight": insight}
    return await caller.call(SERVER, "append_insight", args)


async def create_table(caller: McpCaller, *, query: str) -> Any:
    """Create a new table in the SQLite database"""
    args: dict[str, Any] = {"query": query}
    return await caller.call(SERVER, "create_table", args)


async def describe_table(caller: McpCaller, *, table_name: str) -> Any:
    """Get the schema information for a specific table"""
    args: dict[str, Any] = {"table_name": table_name}
    return await caller.call(SERVER, "describe_table", args)


async def list_tables(caller: McpCaller) -> Any:
    """List all tables in the SQLite database"""
    return await caller.call(SERVER, "list_tables", {})


async def read_query(caller: McpCaller, *, query: str) -> Any:
    """Execute a SELECT query on the SQLite database"""
    args: dict[str, Any] = {"query": query}
    return await caller.call(SERVER, "read_query", args)


async def write_query(caller: McpCaller, *, query: str) -> Any:
    """Execute an INSERT, UPDATE, or DELETE query on the SQLite database"""
    args: dict[str, Any] = {"query": query}
    return await caller.call(SERVER, "write_query", args)
