"""Generated MCP wrappers for the 'deepwiki' server. DO NOT hand-edit signatures.

Generated by mcp-client-kit from a live tools/list. Each function forwards to an
injected McpCaller (see mcp_client_kit.seam); the auth/transport backend is the
caller's concern, not this module's.
"""
from __future__ import annotations

from typing import Any, TypedDict, cast

from mcp_client_kit.seam import McpCaller

SERVER = 'deepwiki'



async def ask_question(caller: McpCaller, *, repoName: Any, question: str) -> Any:
    """Ask any question about a GitHub repository and get an AI-powered, context-grounded response.
    
    Args:
        repoName: GitHub repository or list of repositories (max 10) in owner/repo format
        question: The question to ask about the repository
    """
    args: dict[str, Any] = {"repoName": repoName, "question": question}
    return await caller.call(SERVER, "ask_question", args)


async def read_wiki_contents(caller: McpCaller, *, repoName: str) -> Any:
    """View documentation about a GitHub repository.
    
    Args:
        repoName: GitHub repository in owner/repo format (e.g. "facebook/react")
    """
    args: dict[str, Any] = {"repoName": repoName}
    return await caller.call(SERVER, "read_wiki_contents", args)


async def read_wiki_structure(caller: McpCaller, *, repoName: str) -> Any:
    """Get a list of documentation topics for a GitHub repository.
    
    Args:
        repoName: GitHub repository in owner/repo format (e.g. "facebook/react")
    """
    args: dict[str, Any] = {"repoName": repoName}
    return await caller.call(SERVER, "read_wiki_structure", args)
