"""Generated MCP wrappers for the 'time' server. DO NOT hand-edit signatures.

Generated by mcp-client-kit from a live tools/list. Each function forwards to an
injected McpCaller (see mcp_client_kit.seam); the auth/transport backend is the
caller's concern, not this module's.
"""
from __future__ import annotations

from typing import Any, TypedDict, cast

from mcp_client_kit.seam import McpCaller

SERVER = 'time'



class ConvertedTime(TypedDict, total=False):
    source: dict
    target: dict
    time_difference: str


class CurrentTime(TypedDict, total=False):
    timezone: str
    datetime: str
    day_of_week: str
    is_dst: bool


async def convert_time(caller: McpCaller, *, source_timezone: str, time: str, target_timezone: str) -> ConvertedTime:
    """Convert time between timezones"""
    args: dict[str, Any] = {"source_timezone": source_timezone, "time": time, "target_timezone": target_timezone}
    return cast("ConvertedTime", await caller.call(SERVER, "convert_time", args))


async def get_current_time(caller: McpCaller, *, timezone: str) -> CurrentTime:
    """Get current time in a specific timezone"""
    args: dict[str, Any] = {"timezone": timezone}
    return cast("CurrentTime", await caller.call(SERVER, "get_current_time", args))
