"""Generated MCP wrappers for the 'github' server. DO NOT hand-edit signatures.

Generated by mcp-client-kit from a live tools/list. Each function forwards to an
injected McpCaller (see mcp_client_kit.seam); the auth/transport backend is the
caller's concern, not this module's.
"""
from __future__ import annotations

from typing import Any, TypedDict, cast

from mcp_client_kit.seam import McpCaller

SERVER = 'github'



class Label(TypedDict, total=False):
    color: str
    description: str
    id: str
    name: str


class Release(TypedDict, total=False):
    id: int
    tag_name: str
    target_commitish: str
    name: str
    body: str
    draft: bool
    prerelease: bool
    created_at: str
    published_at: str
    url: str
    html_url: str
    assets_url: str
    upload_url: str
    zipball_url: str
    tarball_url: str
    node_id: str
    immutable: bool


class GitHubUser(TypedDict, total=False):
    login: str
    id: int
    profile_url: str
    avatar_url: str


class Release(TypedDict, total=False):
    id: int
    tag_name: str
    target_commitish: str
    name: str
    body: str
    draft: bool
    prerelease: bool
    created_at: str
    published_at: str
    url: str
    html_url: str
    assets_url: str
    upload_url: str
    zipball_url: str
    tarball_url: str
    node_id: str
    immutable: bool


class GitTag(TypedDict, total=False):
    ref: str
    url: str
    node_id: str


class Issue(TypedDict, total=False):
    number: int
    title: str
    state: str
    state_reason: str
    locked: bool
    html_url: str
    author_association: str
    milestone: str
    comments: int
    created_at: str
    updated_at: str
    closed_at: str
    closed_by: str


class Release(TypedDict, total=False):
    id: int
    tag_name: str
    name: str
    body: str
    html_url: str
    published_at: str
    prerelease: bool
    draft: bool


class TagRef(TypedDict, total=False):
    name: str
    sha: str


class SearchResult(TypedDict, total=False):
    total_count: int
    incomplete_results: bool


class SearchResult(TypedDict, total=False):
    total_count: int
    incomplete_results: bool


class SearchResult(TypedDict, total=False):
    total_count: int
    incomplete_results: bool


class SearchResult(TypedDict, total=False):
    total_count: int
    incomplete_results: bool


class SearchResult(TypedDict, total=False):
    total_count: int
    incomplete_results: bool


async def add_comment_to_pending_review(caller: McpCaller, *, body: str, owner: str, path: str, pullNumber: float, repo: str, subjectType: str, line: float | None = None, side: str | None = None, startLine: float | None = None, startSide: str | None = None) -> Any:
    """Add review comment to the requester's latest pending pull request review. A pending review needs to already exist to call this (check with the user if not sure)."""
    args: dict[str, Any] = {"body": body, "owner": owner, "path": path, "pullNumber": pullNumber, "repo": repo, "subjectType": subjectType}
    if line is not None:
        args["line"] = line
    if side is not None:
        args["side"] = side
    if startLine is not None:
        args["startLine"] = startLine
    if startSide is not None:
        args["startSide"] = startSide
    return await caller.call(SERVER, "add_comment_to_pending_review", args)


async def add_issue_comment(caller: McpCaller, *, body: str, issue_number: float, owner: str, repo: str) -> Any:
    """Add a comment to a specific issue in a GitHub repository. Use this tool to add comments to pull requests as well (in this case pass pull request number as issue_number), but only if user is not asking specifically to add review comments."""
    args: dict[str, Any] = {"body": body, "issue_number": issue_number, "owner": owner, "repo": repo}
    return await caller.call(SERVER, "add_issue_comment", args)


async def add_reply_to_pull_request_comment(caller: McpCaller, *, body: str, commentId: float, owner: str, pullNumber: float, repo: str) -> Any:
    """Add a reply to an existing pull request comment. This creates a new comment that is linked as a reply to the specified comment."""
    args: dict[str, Any] = {"body": body, "commentId": commentId, "owner": owner, "pullNumber": pullNumber, "repo": repo}
    return await caller.call(SERVER, "add_reply_to_pull_request_comment", args)


async def create_branch(caller: McpCaller, *, branch: str, owner: str, repo: str, from_branch: str | None = None) -> Any:
    """Create a new branch in a GitHub repository"""
    args: dict[str, Any] = {"branch": branch, "owner": owner, "repo": repo}
    if from_branch is not None:
        args["from_branch"] = from_branch
    return await caller.call(SERVER, "create_branch", args)


async def create_or_update_file(caller: McpCaller, *, branch: str, content: str, message: str, owner: str, path: str, repo: str, sha: str | None = None) -> Any:
    """Create or update a single file in a GitHub repository. 
    If updating, you should provide the SHA of the file you want to update. Use this tool to create or update a file in a GitHub repository remotely; do not use it for local file operations.
    
    In order to obtain the SHA of original file version before updating, use the following git command:
    git rev-parse <branch>:<path to file>
    
    SHA MUST be provided for existing file updates.
    """
    args: dict[str, Any] = {"branch": branch, "content": content, "message": message, "owner": owner, "path": path, "repo": repo}
    if sha is not None:
        args["sha"] = sha
    return await caller.call(SERVER, "create_or_update_file", args)


async def create_pull_request(caller: McpCaller, *, base: str, head: str, owner: str, repo: str, title: str, body: str | None = None, draft: bool | None = None, maintainer_can_modify: bool | None = None) -> Any:
    """Create a new pull request in a GitHub repository."""
    args: dict[str, Any] = {"base": base, "head": head, "owner": owner, "repo": repo, "title": title}
    if body is not None:
        args["body"] = body
    if draft is not None:
        args["draft"] = draft
    if maintainer_can_modify is not None:
        args["maintainer_can_modify"] = maintainer_can_modify
    return await caller.call(SERVER, "create_pull_request", args)


async def create_repository(caller: McpCaller, *, name: str, autoInit: bool | None = None, description: str | None = None, organization: str | None = None, private: bool | None = None) -> Any:
    """Create a new GitHub repository in your account or specified organization"""
    args: dict[str, Any] = {"name": name}
    if autoInit is not None:
        args["autoInit"] = autoInit
    if description is not None:
        args["description"] = description
    if organization is not None:
        args["organization"] = organization
    if private is not None:
        args["private"] = private
    return await caller.call(SERVER, "create_repository", args)


async def delete_file(caller: McpCaller, *, branch: str, message: str, owner: str, path: str, repo: str) -> Any:
    """Delete a file from a GitHub repository"""
    args: dict[str, Any] = {"branch": branch, "message": message, "owner": owner, "path": path, "repo": repo}
    return await caller.call(SERVER, "delete_file", args)


async def fork_repository(caller: McpCaller, *, owner: str, repo: str, organization: str | None = None) -> Any:
    """Fork a GitHub repository to your account or specified organization"""
    args: dict[str, Any] = {"owner": owner, "repo": repo}
    if organization is not None:
        args["organization"] = organization
    return await caller.call(SERVER, "fork_repository", args)


async def get_commit(caller: McpCaller, *, owner: str, repo: str, sha: str, detail: str | None = None, page: float | None = None, perPage: float | None = None) -> Any:
    """Get details for a commit from a GitHub repository"""
    args: dict[str, Any] = {"owner": owner, "repo": repo, "sha": sha}
    if detail is not None:
        args["detail"] = detail
    if page is not None:
        args["page"] = page
    if perPage is not None:
        args["perPage"] = perPage
    return await caller.call(SERVER, "get_commit", args)


async def get_file_contents(caller: McpCaller, *, owner: str, repo: str, path: str | None = None, ref: str | None = None, sha: str | None = None) -> Any:
    """Get the contents of a file or directory from a GitHub repository"""
    args: dict[str, Any] = {"owner": owner, "repo": repo}
    if path is not None:
        args["path"] = path
    if ref is not None:
        args["ref"] = ref
    if sha is not None:
        args["sha"] = sha
    return await caller.call(SERVER, "get_file_contents", args)


async def get_label(caller: McpCaller, *, name: str, owner: str, repo: str) -> Label:
    """Get a specific label from a repository."""
    args: dict[str, Any] = {"name": name, "owner": owner, "repo": repo}
    return cast("Label", await caller.call(SERVER, "get_label", args))


async def get_latest_release(caller: McpCaller, *, owner: str, repo: str) -> Release:
    """Get the latest release in a GitHub repository"""
    args: dict[str, Any] = {"owner": owner, "repo": repo}
    return cast("Release", await caller.call(SERVER, "get_latest_release", args))


async def get_me(caller: McpCaller) -> GitHubUser:
    """Get details of the authenticated GitHub user. Use this when a request is about the user's own profile for GitHub. Or when information is missing to build other tool calls."""
    return cast("GitHubUser", await caller.call(SERVER, "get_me", {}))


async def get_release_by_tag(caller: McpCaller, *, owner: str, repo: str, tag: str) -> Release:
    """Get a specific release by its tag name in a GitHub repository"""
    args: dict[str, Any] = {"owner": owner, "repo": repo, "tag": tag}
    return cast("Release", await caller.call(SERVER, "get_release_by_tag", args))


async def get_tag(caller: McpCaller, *, owner: str, repo: str, tag: str) -> GitTag:
    """Get details about a specific git tag in a GitHub repository"""
    args: dict[str, Any] = {"owner": owner, "repo": repo, "tag": tag}
    return cast("GitTag", await caller.call(SERVER, "get_tag", args))


async def get_team_members(caller: McpCaller, *, org: str, team_slug: str) -> Any:
    """Get member usernames of a specific team in an organization. Limited to organizations accessible with current credentials"""
    args: dict[str, Any] = {"org": org, "team_slug": team_slug}
    return await caller.call(SERVER, "get_team_members", args)


async def get_teams(caller: McpCaller, *, user: str | None = None) -> Any:
    """Get details of the teams the user is a member of. Limited to organizations accessible with current credentials"""
    args: dict[str, Any] = {}
    if user is not None:
        args["user"] = user
    return await caller.call(SERVER, "get_teams", args)


async def issue_read(caller: McpCaller, *, issue_number: float, method: str, owner: str, repo: str, page: float | None = None, perPage: float | None = None) -> Issue:
    """Get information about a specific issue in a GitHub repository."""
    args: dict[str, Any] = {"issue_number": issue_number, "method": method, "owner": owner, "repo": repo}
    if page is not None:
        args["page"] = page
    if perPage is not None:
        args["perPage"] = perPage
    return cast("Issue", await caller.call(SERVER, "issue_read", args))


async def issue_write(caller: McpCaller, *, method: str, owner: str, repo: str, assignees: list[str] | None = None, body: str | None = None, duplicate_of: float | None = None, issue_fields: list[dict] | None = None, issue_number: float | None = None, labels: list[str] | None = None, milestone: float | None = None, state: str | None = None, state_reason: str | None = None, title: str | None = None, type: str | None = None) -> Any:
    """Create a new or update an existing issue in a GitHub repository."""
    args: dict[str, Any] = {"method": method, "owner": owner, "repo": repo}
    if assignees is not None:
        args["assignees"] = assignees
    if body is not None:
        args["body"] = body
    if duplicate_of is not None:
        args["duplicate_of"] = duplicate_of
    if issue_fields is not None:
        args["issue_fields"] = issue_fields
    if issue_number is not None:
        args["issue_number"] = issue_number
    if labels is not None:
        args["labels"] = labels
    if milestone is not None:
        args["milestone"] = milestone
    if state is not None:
        args["state"] = state
    if state_reason is not None:
        args["state_reason"] = state_reason
    if title is not None:
        args["title"] = title
    if type is not None:
        args["type"] = type
    return await caller.call(SERVER, "issue_write", args)


async def list_branches(caller: McpCaller, *, owner: str, repo: str, page: float | None = None, perPage: float | None = None) -> Any:
    """List branches in a GitHub repository"""
    args: dict[str, Any] = {"owner": owner, "repo": repo}
    if page is not None:
        args["page"] = page
    if perPage is not None:
        args["perPage"] = perPage
    return await caller.call(SERVER, "list_branches", args)


async def list_commits(caller: McpCaller, *, owner: str, repo: str, author: str | None = None, page: float | None = None, path: str | None = None, perPage: float | None = None, sha: str | None = None, since: str | None = None, until: str | None = None) -> Any:
    """Get list of commits of a branch in a GitHub repository. Returns at least 30 results per page by default, but can return more if specified using the perPage parameter (up to 100)."""
    args: dict[str, Any] = {"owner": owner, "repo": repo}
    if author is not None:
        args["author"] = author
    if page is not None:
        args["page"] = page
    if path is not None:
        args["path"] = path
    if perPage is not None:
        args["perPage"] = perPage
    if sha is not None:
        args["sha"] = sha
    if since is not None:
        args["since"] = since
    if until is not None:
        args["until"] = until
    return await caller.call(SERVER, "list_commits", args)


async def list_issue_fields(caller: McpCaller, *, owner: str, repo: str | None = None) -> Any:
    """List issue fields for a repository or organization. Returns field definitions including name, type (text, number, date, single_select), and for single_select fields the list of valid option names. When repo is omitted, returns org-level fields directly."""
    args: dict[str, Any] = {"owner": owner}
    if repo is not None:
        args["repo"] = repo
    return await caller.call(SERVER, "list_issue_fields", args)


async def list_issue_types(caller: McpCaller, *, owner: str) -> Any:
    """List supported issue types for repository owner (organization)."""
    args: dict[str, Any] = {"owner": owner}
    return await caller.call(SERVER, "list_issue_types", args)


async def list_issues(caller: McpCaller, *, owner: str, repo: str, after: str | None = None, direction: str | None = None, field_filters: list[dict] | None = None, labels: list[str] | None = None, orderBy: str | None = None, perPage: float | None = None, since: str | None = None, state: str | None = None) -> Any:
    """List issues in a GitHub repository. For pagination, use the 'endCursor' from the previous response's 'pageInfo' in the 'after' parameter."""
    args: dict[str, Any] = {"owner": owner, "repo": repo}
    if after is not None:
        args["after"] = after
    if direction is not None:
        args["direction"] = direction
    if field_filters is not None:
        args["field_filters"] = field_filters
    if labels is not None:
        args["labels"] = labels
    if orderBy is not None:
        args["orderBy"] = orderBy
    if perPage is not None:
        args["perPage"] = perPage
    if since is not None:
        args["since"] = since
    if state is not None:
        args["state"] = state
    return await caller.call(SERVER, "list_issues", args)


async def list_pull_requests(caller: McpCaller, *, owner: str, repo: str, base: str | None = None, direction: str | None = None, head: str | None = None, page: float | None = None, perPage: float | None = None, sort: str | None = None, state: str | None = None) -> Any:
    """List pull requests in a GitHub repository. If the user specifies an author, then DO NOT use this tool and use the search_pull_requests tool instead."""
    args: dict[str, Any] = {"owner": owner, "repo": repo}
    if base is not None:
        args["base"] = base
    if direction is not None:
        args["direction"] = direction
    if head is not None:
        args["head"] = head
    if page is not None:
        args["page"] = page
    if perPage is not None:
        args["perPage"] = perPage
    if sort is not None:
        args["sort"] = sort
    if state is not None:
        args["state"] = state
    return await caller.call(SERVER, "list_pull_requests", args)


async def list_releases(caller: McpCaller, *, owner: str, repo: str, page: float | None = None, perPage: float | None = None) -> list[Release]:
    """List releases in a GitHub repository"""
    args: dict[str, Any] = {"owner": owner, "repo": repo}
    if page is not None:
        args["page"] = page
    if perPage is not None:
        args["perPage"] = perPage
    return cast("list[Release]", await caller.call(SERVER, "list_releases", args))


async def list_repository_collaborators(caller: McpCaller, *, owner: str, repo: str, affiliation: str | None = None, page: float | None = None, perPage: float | None = None) -> Any:
    """List collaborators of a GitHub repository. Results are paginated; the response includes `nextPage`, `prevPage`, `firstPage`, and `lastPage` fields. To get the next page, use the `nextPage` value as the `page` parameter."""
    args: dict[str, Any] = {"owner": owner, "repo": repo}
    if affiliation is not None:
        args["affiliation"] = affiliation
    if page is not None:
        args["page"] = page
    if perPage is not None:
        args["perPage"] = perPage
    return await caller.call(SERVER, "list_repository_collaborators", args)


async def list_tags(caller: McpCaller, *, owner: str, repo: str, page: float | None = None, perPage: float | None = None) -> list[TagRef]:
    """List git tags in a GitHub repository"""
    args: dict[str, Any] = {"owner": owner, "repo": repo}
    if page is not None:
        args["page"] = page
    if perPage is not None:
        args["perPage"] = perPage
    return cast("list[TagRef]", await caller.call(SERVER, "list_tags", args))


async def merge_pull_request(caller: McpCaller, *, owner: str, pullNumber: float, repo: str, commit_message: str | None = None, commit_title: str | None = None, merge_method: str | None = None) -> Any:
    """Merge a pull request in a GitHub repository."""
    args: dict[str, Any] = {"owner": owner, "pullNumber": pullNumber, "repo": repo}
    if commit_message is not None:
        args["commit_message"] = commit_message
    if commit_title is not None:
        args["commit_title"] = commit_title
    if merge_method is not None:
        args["merge_method"] = merge_method
    return await caller.call(SERVER, "merge_pull_request", args)


async def pull_request_read(caller: McpCaller, *, method: str, owner: str, pullNumber: float, repo: str, after: str | None = None, page: float | None = None, perPage: float | None = None) -> Any:
    """Get information on a specific pull request in GitHub repository."""
    args: dict[str, Any] = {"method": method, "owner": owner, "pullNumber": pullNumber, "repo": repo}
    if after is not None:
        args["after"] = after
    if page is not None:
        args["page"] = page
    if perPage is not None:
        args["perPage"] = perPage
    return await caller.call(SERVER, "pull_request_read", args)


async def pull_request_review_write(caller: McpCaller, *, method: str, owner: str, pullNumber: float, repo: str, body: str | None = None, commitID: str | None = None, event: str | None = None, threadId: str | None = None) -> Any:
    """Create and/or submit, delete review of a pull request.
    
    Available methods:
    - create: Create a new review of a pull request. If "event" parameter is provided, the review is submitted. If "event" is omitted, a pending review is created.
    - submit_pending: Submit an existing pending review of a pull request. This requires that a pending review exists for the current user on the specified pull request. The "body" and "event" parameters are used when submitting the review.
    - delete_pending: Delete an existing pending review of a pull request. This requires that a pending review exists for the current user on the specified pull request.
    - resolve_thread: Resolve a review thread. Requires only "threadId" parameter with the thread's node ID (e.g., PRRT_kwDOxxx). The owner, repo, and pullNumber parameters are not used for this method. Resolving an already-resolved thread is a no-op.
    - unresolve_thread: Unresolve a previously resolved review thread. Requires only "threadId" parameter. The owner, repo, and pullNumber parameters are not used for this method. Unresolving an already-unresolved thread is a no-op.
    """
    args: dict[str, Any] = {"method": method, "owner": owner, "pullNumber": pullNumber, "repo": repo}
    if body is not None:
        args["body"] = body
    if commitID is not None:
        args["commitID"] = commitID
    if event is not None:
        args["event"] = event
    if threadId is not None:
        args["threadId"] = threadId
    return await caller.call(SERVER, "pull_request_review_write", args)


async def push_files(caller: McpCaller, *, branch: str, files: list[dict], message: str, owner: str, repo: str) -> Any:
    """Push multiple files to a GitHub repository in a single commit"""
    args: dict[str, Any] = {"branch": branch, "files": files, "message": message, "owner": owner, "repo": repo}
    return await caller.call(SERVER, "push_files", args)


async def request_copilot_review(caller: McpCaller, *, owner: str, pullNumber: float, repo: str) -> Any:
    """Request a GitHub Copilot code review for a pull request. Use this for automated feedback on pull requests, usually before requesting a human reviewer."""
    args: dict[str, Any] = {"owner": owner, "pullNumber": pullNumber, "repo": repo}
    return await caller.call(SERVER, "request_copilot_review", args)


async def run_secret_scanning(caller: McpCaller, *, files: Any, owner: str, repo: str) -> Any:
    """Scan files, content, or recent changes for secrets such as API keys, passwords, tokens, and credentials.
    
    This tool is intended for targeted scans of specific files, snippets, or diffs provided directly as content. The files parameter accepts either a single string or an array of strings containing raw file contents or diff hunks, and returns detected secrets with their locations and related secret scanning metadata. Content must not be empty. For full repository scanning, other mechanisms are available.
    
    Caveats:
    
    - Only files within the codebase should be scanned. Files outside of the codebase should not be sent.
    - Files listed in .gitignore should be skipped.
    """
    args: dict[str, Any] = {"files": files, "owner": owner, "repo": repo}
    return await caller.call(SERVER, "run_secret_scanning", args)


async def search_code(caller: McpCaller, *, query: str, order: str | None = None, page: float | None = None, perPage: float | None = None, sort: str | None = None) -> SearchResult:
    """Fast and precise code search across ALL GitHub repositories using GitHub's native search engine. Best for finding exact symbols, functions, classes, or specific code patterns."""
    args: dict[str, Any] = {"query": query}
    if order is not None:
        args["order"] = order
    if page is not None:
        args["page"] = page
    if perPage is not None:
        args["perPage"] = perPage
    if sort is not None:
        args["sort"] = sort
    return cast("SearchResult", await caller.call(SERVER, "search_code", args))


async def search_commits(caller: McpCaller, *, query: str, order: str | None = None, page: float | None = None, perPage: float | None = None, sort: str | None = None) -> Any:
    """Search for commits across GitHub repositories using GitHub's commit search syntax. Useful for finding specific changes, authors, or messages across one or many repositories. Searches the default branch only."""
    args: dict[str, Any] = {"query": query}
    if order is not None:
        args["order"] = order
    if page is not None:
        args["page"] = page
    if perPage is not None:
        args["perPage"] = perPage
    if sort is not None:
        args["sort"] = sort
    return await caller.call(SERVER, "search_commits", args)


async def search_issues(caller: McpCaller, *, query: str, order: str | None = None, owner: str | None = None, page: float | None = None, perPage: float | None = None, repo: str | None = None, sort: str | None = None) -> SearchResult:
    """Search for issues in GitHub repositories using issues search syntax already scoped to is:issue"""
    args: dict[str, Any] = {"query": query}
    if order is not None:
        args["order"] = order
    if owner is not None:
        args["owner"] = owner
    if page is not None:
        args["page"] = page
    if perPage is not None:
        args["perPage"] = perPage
    if repo is not None:
        args["repo"] = repo
    if sort is not None:
        args["sort"] = sort
    return cast("SearchResult", await caller.call(SERVER, "search_issues", args))


async def search_pull_requests(caller: McpCaller, *, query: str, order: str | None = None, owner: str | None = None, page: float | None = None, perPage: float | None = None, repo: str | None = None, sort: str | None = None) -> SearchResult:
    """Search for pull requests in GitHub repositories using issues search syntax already scoped to is:pr"""
    args: dict[str, Any] = {"query": query}
    if order is not None:
        args["order"] = order
    if owner is not None:
        args["owner"] = owner
    if page is not None:
        args["page"] = page
    if perPage is not None:
        args["perPage"] = perPage
    if repo is not None:
        args["repo"] = repo
    if sort is not None:
        args["sort"] = sort
    return cast("SearchResult", await caller.call(SERVER, "search_pull_requests", args))


async def search_repositories(caller: McpCaller, *, query: str, minimal_output: bool | None = None, order: str | None = None, page: float | None = None, perPage: float | None = None, sort: str | None = None) -> SearchResult:
    """Find GitHub repositories by name, description, readme, topics, or other metadata. Perfect for discovering projects, finding examples, or locating specific repositories across GitHub."""
    args: dict[str, Any] = {"query": query}
    if minimal_output is not None:
        args["minimal_output"] = minimal_output
    if order is not None:
        args["order"] = order
    if page is not None:
        args["page"] = page
    if perPage is not None:
        args["perPage"] = perPage
    if sort is not None:
        args["sort"] = sort
    return cast("SearchResult", await caller.call(SERVER, "search_repositories", args))


async def search_users(caller: McpCaller, *, query: str, order: str | None = None, page: float | None = None, perPage: float | None = None, sort: str | None = None) -> SearchResult:
    """Find GitHub users by username, real name, or other profile information. Useful for locating developers, contributors, or team members."""
    args: dict[str, Any] = {"query": query}
    if order is not None:
        args["order"] = order
    if page is not None:
        args["page"] = page
    if perPage is not None:
        args["perPage"] = perPage
    if sort is not None:
        args["sort"] = sort
    return cast("SearchResult", await caller.call(SERVER, "search_users", args))


async def sub_issue_write(caller: McpCaller, *, issue_number: float, method: str, owner: str, repo: str, sub_issue_id: float, after_id: float | None = None, before_id: float | None = None, replace_parent: bool | None = None) -> Any:
    """Add a sub-issue to a parent issue in a GitHub repository."""
    args: dict[str, Any] = {"issue_number": issue_number, "method": method, "owner": owner, "repo": repo, "sub_issue_id": sub_issue_id}
    if after_id is not None:
        args["after_id"] = after_id
    if before_id is not None:
        args["before_id"] = before_id
    if replace_parent is not None:
        args["replace_parent"] = replace_parent
    return await caller.call(SERVER, "sub_issue_write", args)


async def update_pull_request(caller: McpCaller, *, owner: str, pullNumber: float, repo: str, base: str | None = None, body: str | None = None, draft: bool | None = None, maintainer_can_modify: bool | None = None, reviewers: list[str] | None = None, state: str | None = None, title: str | None = None) -> Any:
    """Update an existing pull request in a GitHub repository."""
    args: dict[str, Any] = {"owner": owner, "pullNumber": pullNumber, "repo": repo}
    if base is not None:
        args["base"] = base
    if body is not None:
        args["body"] = body
    if draft is not None:
        args["draft"] = draft
    if maintainer_can_modify is not None:
        args["maintainer_can_modify"] = maintainer_can_modify
    if reviewers is not None:
        args["reviewers"] = reviewers
    if state is not None:
        args["state"] = state
    if title is not None:
        args["title"] = title
    return await caller.call(SERVER, "update_pull_request", args)


async def update_pull_request_branch(caller: McpCaller, *, owner: str, pullNumber: float, repo: str, expectedHeadSha: str | None = None) -> Any:
    """Update the branch of a pull request with the latest changes from the base branch."""
    args: dict[str, Any] = {"owner": owner, "pullNumber": pullNumber, "repo": repo}
    if expectedHeadSha is not None:
        args["expectedHeadSha"] = expectedHeadSha
    return await caller.call(SERVER, "update_pull_request_branch", args)
