"""Generated MCP wrappers for the 'huggingface' server. DO NOT hand-edit signatures.

Generated by mcp-client-kit from a live tools/list. Each function forwards to an
injected McpCaller (see mcp_client_kit.seam); the auth/transport backend is the
caller's concern, not this module's.
"""
from __future__ import annotations

from typing import Any, TypedDict, cast

from mcp_client_kit.seam import McpCaller

SERVER = 'huggingface'



async def gr1_z_image_turbo_generate(caller: McpCaller, *, prompt: str | None = None, resolution: str | None = None, seed: int | None = None, steps: float | None = None, shift: float | None = None, random_seed: bool | None = None) -> Any:
    """Generate an image using the Z-Image model based on the provided prompt and settings. This function is triggered when the user clicks the "Generate" button. It processes the input prompt (optionally enhancing it), configures generation parameters, and produces an image using the Z-Image diffusion transformer pipeline. Returns: tuple: (gallery_images, seed_str, seed_int), - seed_str: String representation of the seed used for generation, - seed_int: Integer representation of the seed used for generation (from mcp-tools/Z-Image-Turbo)"""
    args: dict[str, Any] = {}
    if prompt is not None:
        args["prompt"] = prompt
    if resolution is not None:
        args["resolution"] = resolution
    if seed is not None:
        args["seed"] = seed
    if steps is not None:
        args["steps"] = steps
    if shift is not None:
        args["shift"] = shift
    if random_seed is not None:
        args["random_seed"] = random_seed
    return await caller.call(SERVER, "gr1_z_image_turbo_generate", args)


async def hf_doc_fetch(caller: McpCaller, *, doc_url: str, offset: float | None = None) -> Any:
    """Fetch a document from the Hugging Face or Gradio documentation library. For large documents, use offset to get subsequent chunks."""
    args: dict[str, Any] = {"doc_url": doc_url}
    if offset is not None:
        args["offset"] = offset
    return await caller.call(SERVER, "hf_doc_fetch", args)


async def hf_doc_search(caller: McpCaller, *, query: str, product: str | None = None) -> Any:
    """Search and Discover Hugging Face Product and Library documentation. Send an empty query to discover structure and navigation instructions. Knowledge up-to-date as at 14 June 2026. Combine with the Product filter to focus results."""
    args: dict[str, Any] = {"query": query}
    if product is not None:
        args["product"] = product
    return await caller.call(SERVER, "hf_doc_search", args)


async def hf_whoami(caller: McpCaller) -> Any:
    """Hugging Face tools are being used anonymously and may be rate limited. Call this tool for instructions on joining and authenticating."""
    return await caller.call(SERVER, "hf_whoami", {})


async def hub_repo_details(caller: McpCaller, *, repo_ids: list[str], repo_type: str | None = None, operations: list[str] | None = None, config: str | None = None, split: str | None = None, offset: int | None = None, limit: int | None = None) -> Any:
    """Get details for one or more Hugging Face repos (model, dataset, or space). Auto-detects type unless specified. For datasets, use operations: overview, dataset_structure, dataset_preview. Use dataset_structure first to discover configs, splits, sizes, and schema. Use dataset_preview only when config and split are known, unless the dataset has a single config/split."""
    args: dict[str, Any] = {"repo_ids": repo_ids}
    if repo_type is not None:
        args["repo_type"] = repo_type
    if operations is not None:
        args["operations"] = operations
    if config is not None:
        args["config"] = config
    if split is not None:
        args["split"] = split
    if offset is not None:
        args["offset"] = offset
    if limit is not None:
        args["limit"] = limit
    return await caller.call(SERVER, "hub_repo_details", args)


async def hub_repo_search(caller: McpCaller, *, query: str | None = None, repo_types: list[str] | None = None, author: str | None = None, filters: list[str] | None = None, sort: str | None = None, limit: float | None = None) -> Any:
    """Search Hugging Face repositories with a shared query interface. You can target models, datasets, spaces, or aggregate across multiple repo types in one call. Use space_search for semantic-first discovery of Spaces. Include links to repositories in your response."""
    args: dict[str, Any] = {}
    if query is not None:
        args["query"] = query
    if repo_types is not None:
        args["repo_types"] = repo_types
    if author is not None:
        args["author"] = author
    if filters is not None:
        args["filters"] = filters
    if sort is not None:
        args["sort"] = sort
    if limit is not None:
        args["limit"] = limit
    return await caller.call(SERVER, "hub_repo_search", args)


async def paper_search(caller: McpCaller, *, query: str, results_limit: float | None = None, concise_only: bool | None = None) -> Any:
    """Find Machine Learning research papers on the Hugging Face hub. Include 'Link to paper' When presenting the results. Consider whether tabulating results matches user intent."""
    args: dict[str, Any] = {"query": query}
    if results_limit is not None:
        args["results_limit"] = results_limit
    if concise_only is not None:
        args["concise_only"] = concise_only
    return await caller.call(SERVER, "paper_search", args)


async def space_search(caller: McpCaller, *, query: str, limit: float | None = None, mcp: bool | None = None) -> Any:
    """Find Hugging Face Spaces using semantic search. IMPORTANT Only MCP Servers can be used with the dynamic_space toolInclude links to the Space when presenting the results."""
    args: dict[str, Any] = {"query": query}
    if limit is not None:
        args["limit"] = limit
    if mcp is not None:
        args["mcp"] = mcp
    return await caller.call(SERVER, "space_search", args)
